### ISSUE TITLE
RubyVM::DebugInspector (NameError)

### ISSUE THREAD

**Issue by JamesDullaghan** [banister/binding_of_caller#39]
``` powershell
/Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/binding_of_caller-0.7.2/lib/binding_of_caller/mri2.rb:21:in `callers': uninitialized constant RubyVM::DebugInspector (NameError)
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/better_errors-0.3.2/lib/better_errors/core_ext/exception.rb:9:in `block in <class:Exception>'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-3.2.16/lib/active_support/testing/deprecation.rb:39:in `new'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-3.2.16/lib/active_support/testing/deprecation.rb:39:in `require'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-3.2.16/lib/active_support/testing/deprecation.rb:39:in `<top (required)>'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-3.2.16/lib/active_support/test_case.rb:4:in `require'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-3.2.16/lib/active_support/test_case.rb:4:in `<top (required)>'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/actionpack-3.2.16/lib/action_controller/test_case.rb:355:in `<module:ActionController>'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/actionpack-3.2.16/lib/action_controller/test_case.rb:7:in `<top (required)>'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/shoulda-matchers-1.4.1/lib/shoulda/matchers/integrations/test_unit.rb:6:in `<top (required)>'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/shoulda-matchers-1.4.1/lib/shoulda/matchers.rb:8:in `require'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/shoulda-matchers-1.4.1/lib/shoulda/matchers.rb:8:in `<top (required)>'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/shoulda-matchers-1.4.1/lib/shoulda-matchers.rb:1:in `require'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/shoulda-matchers-1.4.1/lib/shoulda-matchers.rb:1:in `<top (required)>'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
    from /Users/hippo/Development/responsive/config/application.rb:13:in `<top (required)>'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/railties-3.2.16/lib/rails/commands.rb:53:in `require'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/railties-3.2.16/lib/rails/commands.rb:53:in `block in <top (required)>'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/railties-3.2.16/lib/rails/commands.rb:50:in `tap'
    from /Users/hippo/.rvm/gems/ruby-2.0.0-p353/gems/railties-3.2.16/lib/rails/commands.rb:50:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Any idea what is going on here?

**Comment by prpetten** [comment]
Looks like this issue is solved.  If anyone needs to reopen, let me know.
