### ISSUE TITLE
Undefined method `caller_locations'

### ISSUE THREAD

**Issue by bvogel** [banister/binding_of_caller#51]
Hi, I'm trying to switch a Rails 4.1.6 app from MRI 2.1.3 to Rubinius 2.2.10 but I get an exception in combination with better_errors 2.0.0:

```
NoMethodError - undefined method `caller_locations' on an instance of ActionController::RoutingError.:
  kernel/delta/kernel.rb:78:in `caller_locations (method_missing)'
  better_errors (2.0.0) lib/better_errors/exception_extension.rb:6:in `set_backtrace'
  kernel/common/exception.rb:139:in `set_context'
  kernel/delta/kernel.rb:25:in `raise'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:71:in `controller'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:46:in `call'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:73:in `call'
  kernel/bootstrap/array.rb:76:in `each'
  actionpack (4.1.6) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.6) lib/action_dispatch/routing/route_set.rb:678:in `call'
  bullet (4.13.2) lib/bullet/rack.rb:12:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.6) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:29:in `call'
  activesupport (4.1.6) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.6) lib/rails/rack/logger.rb:20:in `call'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.6) lib/rails/rack/logger.rb:20:in `call_without_quiet_assets (call)'
  quiet_assets (1.0.3) lib/quiet_assets.rb:23:in `call (call_with_quiet_assets)'
  actionpack (4.1.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  rack-mini-profiler (0.9.2) lib/mini_profiler/profiler.rb:300:in `call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
  railties (4.1.6) lib/rails/engine.rb:514:in `call'
  railties (4.1.6) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  webrick (1.3.1) lib/webrick/httpserver.rb:138:in `service'
  webrick (1.3.1) lib/webrick/httpserver.rb:94:in `run'
  webrick (1.3.1) lib/webrick/server.rb:191:in `start_thread'
  kernel/bootstrap/proc.rb:20:in `call'
  kernel/bootstrap/thread.rb:391:in `__run__'
```

I'm blaming `binding_of_caller` as better_errors will work without it. Please inform me if any additional information is needed.

**Comment by prpetten** [comment]
Closing this, as there hasn't been any updates to Rubinus in the past 4 years or so.
